### ISSUE TITLE
[Question] Is there a check for if a Itemframe contains a map from maplands?

### ISSUE THREAD

**Issue by Andre601** [bergerhealer/Maplands#14]
Question is in the title.
I wanted to ask, if there is a way, to check, if a itemframe has a map and if that map is from maplands.
I want to add a check to maplands that prevents the rotation of a map in a itemframe.
But I can't find out if (and if yes, where) maplands has such a check.

Could it be `MapUtil.isTile()`?

**Comment by Andre601** [comment]
I implemented a `PlayerInteractEntityEvent` and right now it listens for any item rotation that happens in an ItemFrame and is with a map...
Only thing missing is the check for if the map is actually from Maplands...

Also while doing that did I find an interesting bug/issue.
Mapland maps, that are in ItemFrames, are no longer seen as such when you restart the server.
This also applies when you remove the map and re-add it to the ItemFrame.

Note that the map in your hand still functions properly, but putting it in the ItemFrame doesn't *sync* them like it does the first time.

**Comment by Andre601** [comment]
Another update:
I tried to get the tags that are set for an item through `ItemUtil.getMetaTag(ItemStack)` in this method here:
```java
    static boolean isMaplandMap(Entity entity){
        if(!(entity instanceof ItemFrame)) return false;

        ItemFrame itemFrame = (ItemFrame)entity;
        ItemStack itemStack = itemFrame.getItem();
        if(!itemStack.getType().equals(Material.MAP)) return false;

        CommonTagCompound tags = ItemUtil.getMetaTag(itemStack);
        if(tags == null) return false;

        return tags.containsKey("mapDisplayClass");
    }
```

But this does not work since the tag is always null.
Checking the NBT-data with Minecraft's `/entitydata` command shows, that the Item in the Item frame has the tag `mapDisplayClass`
Do I miss here something or does the used ItemUtil method return something completely different?

**Comment by bergerkiller** [comment]
The issue is likely that the itemstack youre getting isnt a CraftItemStack but a bukkit one, which doesnt have NBT data. For this reason BKC uses a more convoluted method to access the item:

https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/java/com/bergerkiller/bukkit/common/internal/CommonMapController.java#L1748

or:

`EntityItemFrameHandle.fromBukkit(itemFrame).getItem()`

I think a method to retrieve the MapDisplay 'displayed' in an item frame would be handy. So Ive added that. But it might not be 100% useful to you, since it may return no map display instances when no players are nearby viewing it.

https://github.com/bergerhealer/BKCommonLib/commit/f6784a20ce2175945d224e11e4f1095501e1cc4c

https://ci.mg-dev.eu/job/BKCommonLib/520/
