### ISSUE TITLE
Void (Air) is not rendered

### ISSUE THREAD

**Issue by Andre601** [bergerhealer/Maplands#20]
When you have a world, which f.e. is surrounded by void (air) does Maplands not update the rendered blocks in that case, which results in an image like shown below.

I would suggest rendering the void as a sort of colour like blue, or perhaps black.

## Images
The world
![2019-11-01_14 00 05](https://user-images.githubusercontent.com/11576465/68026416-f7e58000-fcaf-11e9-9c95-224a3bc3f486.png)

How Maplands renders it
![2019-11-01_13 59 33](https://user-images.githubusercontent.com/11576465/68026414-f7e58000-fcaf-11e9-97f3-019b0ac12853.png)

**Comment by bergerkiller** [comment]
I can add a configurable background color for maps, defaulting to transparent. Filling the map in such a color before rendering is trivial

**Comment by bergerkiller** [comment]
Its been a while but Ive made changes so that the background color can be configured. https://github.com/bergerhealer/Maplands/commit/48e9eabbfaed682a293112d6fffa49acdf9aca95

Test it out with this version: https://ci.mg-dev.eu/job/Maplands/44/
And change backgroundColor to 'black' (or something else) in config.yml
